export const UI = {
  headerTitle: "Your Notes",
  keyboardHint: "⌘/Ctrl + Enter",

  emptyStateTitle: "No notes yet",
  emptyStateBody: "Add your first note below with the +.",

  menuEdit: "Edit",
  menuDelete: "Delete",

  ariaEditNote: "Edit note",
  ariaDeleteNote: "Delete note",

  titleEdit: "Edit",
  titleDelete: "Delete",
  delete: "Delete",
  cancel: "Cancel",
  save: "Save",
  continue: "Continue",
  passphrase: "Passphrase",
  recoveryKey: "Recovery Key",
  savedRecoveryKeyConfirm: "I have saved this recovery key.",
  copy: "Copy",
  copied: "Copied!",
  ariaCopyRecoveryKey: "Copy recovery key",
  titleCopyRecoveryKey: "Copy recovery key",
  copyFailedAlert: "Copy failed. Please select and copy manually.",
  recoveryKeyExplanation: "This key can unlock your vault if you forget your passphrase. It will be shown only once.",
  saveRecoveryKeyPrompt: "Save your recovery key",
  unlockFailedAlert: "Unlock failed. Check your passphrase/recovery key.",
  enterPassphrasePrompt: "Enter your passphrase to unlock your vault.",
  enterRecoveryKeyPrompt: "Enter your recovery key to unlock your vault.",
  passphraseMinimumHint: "Passphrase should be at least 8 characters.",
  unlockVaultPrompt: "Unlock your vault",
  createVaultPrompt: "Create your vault",
  previewMode: "Preview Mode",
  editMode: "Edit Mode",
  preview: "Preview",
  confirmDeleteBody: "Are you sure you want to delete this note? This action cannot be undone.",
  confirmDeleteTitle: "Confirm Delete",
  titlePlaceholder: "Title",
    bodyPlaceholder: "Write your note here...",
  moreText: "...",
    untitled: "Untitled",
  notesCount: (n: number) => n === 1 ? "1 note" : `${n} notes`,
} as const;
